//! `Param<'a>` — runtime values that satisfy `%var` / `%N` atoms.
//!
//! Phase E (murphy-aow) introduces NodePattern atoms `%name` (tPARAM_NAMED) and
//! `%1`/`%2` (tPARAM_NUMBER) that bind to **runtime** values supplied by the
//! caller — typically a cop's [`CopOptions`] field for named params, or an
//! explicit positional argument for `%N`. This module defines the runtime
//! representation (`Param`), the conversion bridge from `CopOptions` field
//! types (`IntoParam`), and the central comparison helper
//! ([`match_lit_against_param`]) used by both the C-backend matcher
//! ([`crate::matches`]) and code generated by the B-backend macro
//! (`def_node_matcher!`).
//!
//! ## Type matrix
//!
//! | `CopOptions` field type    | `Param` variant   | Compared against subject |
//! |----------------------------|-------------------|--------------------------|
//! | `&String`                  | `Str(&str)`       | `Sym(s)` / `Str(s)` — equality |
//! | `&Vec<String>`             | `StrSet(&[String])` | `Sym(s)` / `Str(s)` — `contains` |
//! | `i64` (`Copy`)             | `Int(i64)`        | `Int(n)` — equality |
//! | `&Vec<i64>`                | `IntSet(&[i64])`  | `Int(n)` — `contains` |
//! | `bool` (`Copy`)            | `Bool(bool)`      | `True` / `False` — equality |
//! | `&E: CopOptionEnum`        | `Str(&str)`       | `Sym(s)` — equality with `as_str()` |
//! | `&Option<T>` where `&T: IntoParam` | inner or `None` | `None` → always miss |
//!
//! Type-mismatched comparisons (e.g. `%method: i64` against `Lit::Sym(...)`)
//! return `false` — runtime miss, not panic. This matches RuboCop's fail-soft
//! behaviour when a `%var` resolves to a type the pattern slot can't accept.
//!
//! ## Why a separate `LitView` enum
//!
//! [`match_lit_against_param`] takes a [`LitView`] rather than an AST [`NodeKind`]
//! so that the helper has no `murphy-ast` dependency on call sites where the
//! subject is already disassembled (e.g. the B-backend macro lowers a fixed
//! [`NodeKind::Sym(StringId)`](murphy_ast::NodeKind) call into a `LitView::Str(&str)`
//! it already had to compute). Both backends provide their own
//! `LitView::from_kind(&NodeKind, interner)` helper next to their pattern code.

/// Runtime value supplied for a `%var` (named) or `%N` (positional) atom.
///
/// Lifetime `'a` is tied to whatever owns the underlying string / slice — for
/// named params, the `CopOptions` value the caller decoded in the same scope.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Param<'a> {
    /// Single string. Matches `LitView::Sym(s)` or `LitView::Str(s)` when `s == self`.
    Str(&'a str),
    /// Set of strings. Matches when the subject string is contained in the slice.
    StrSet(&'a [String]),
    /// Single integer. Matches `LitView::Int(n)` when `n == self`.
    Int(i64),
    /// Set of integers. Matches when the subject int is contained in the slice.
    IntSet(&'a [i64]),
    /// Boolean. Matches `LitView::True` for `true`, `LitView::False` for `false`.
    Bool(bool),
    /// `Option<T>::None`. Always a miss; produced from `(&Option::<T>::None).into_param()`.
    None,
}

/// A subject's literal-atom shape, decomposed enough to compare against a
/// [`Param`] without dragging in the full AST surface.
///
/// Backends construct this from their own AST representation (the C matcher
/// from a `murphy_ast::NodeKind`, the B-macro from a fixed-slot `NodeKind`
/// payload it already has access to) and pass it to
/// [`match_lit_against_param`].
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LitView<'a> {
    Sym(&'a str),
    Str(&'a str),
    Int(i64),
    True,
    False,
    Nil,
}

/// Conversion from a `CopOptions` field reference to a [`Param`] view.
///
/// Implementations land here for every field type Murphy's `#[derive(CopOptions)]`
/// already supports (`String`, `Vec<String>`, `i64`, `bool`, `Option<T>`,
/// `CopOptionEnum`), plus `Vec<i64>` to forward-pave for future option-derive
/// support. Field types without an `IntoParam` impl produce a compile error
/// at the `def_node_matcher!` call site that references them — a feature, not a
/// bug: the cop author finds out at compile time that a `%var` references a
/// non-comparable field instead of silently always missing at runtime.
pub trait IntoParam<'a> {
    fn into_param(self) -> Param<'a>;
}

impl<'a> IntoParam<'a> for &'a String {
    fn into_param(self) -> Param<'a> {
        Param::Str(self.as_str())
    }
}

impl<'a> IntoParam<'a> for &'a str {
    fn into_param(self) -> Param<'a> {
        Param::Str(self)
    }
}

impl<'a> IntoParam<'a> for &'a Vec<String> {
    fn into_param(self) -> Param<'a> {
        Param::StrSet(self.as_slice())
    }
}

impl<'a> IntoParam<'a> for &'a [String] {
    fn into_param(self) -> Param<'a> {
        Param::StrSet(self)
    }
}

impl<'a> IntoParam<'a> for i64 {
    fn into_param(self) -> Param<'a> {
        Param::Int(self)
    }
}

impl<'a> IntoParam<'a> for &'a i64 {
    fn into_param(self) -> Param<'a> {
        Param::Int(*self)
    }
}

impl<'a> IntoParam<'a> for &'a Vec<i64> {
    fn into_param(self) -> Param<'a> {
        Param::IntSet(self.as_slice())
    }
}

impl<'a> IntoParam<'a> for &'a [i64] {
    fn into_param(self) -> Param<'a> {
        Param::IntSet(self)
    }
}

impl<'a> IntoParam<'a> for bool {
    fn into_param(self) -> Param<'a> {
        Param::Bool(self)
    }
}

impl<'a> IntoParam<'a> for &'a bool {
    fn into_param(self) -> Param<'a> {
        Param::Bool(*self)
    }
}

impl<'a, T> IntoParam<'a> for &'a Option<T>
where
    &'a T: IntoParam<'a>,
{
    fn into_param(self) -> Param<'a> {
        match self {
            Some(t) => t.into_param(),
            None => Param::None,
        }
    }
}

/// Compare a subject [`LitView`] against a [`Param`]. Returns `true` only when
/// the shapes are compatible AND the values agree. A `LitView` `None` (no
/// literal extracted from the subject) is always a miss.
pub fn match_lit_against_param(lit: Option<LitView<'_>>, param: &Param<'_>) -> bool {
    let Some(lit) = lit else { return false };
    match (lit, param) {
        (LitView::Sym(s) | LitView::Str(s), Param::Str(t)) => s == *t,
        (LitView::Sym(s) | LitView::Str(s), Param::StrSet(v)) => v.iter().any(|t| t == s),
        (LitView::Int(n), Param::Int(t)) => n == *t,
        (LitView::Int(n), Param::IntSet(v)) => v.contains(&n),
        (LitView::True, Param::Bool(true)) => true,
        (LitView::False, Param::Bool(false)) => true,
        (_, Param::None) => false,
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn str_vs_sym_str_equality() {
        assert!(match_lit_against_param(
            Some(LitView::Sym("foo")),
            &Param::Str("foo")
        ));
        assert!(match_lit_against_param(
            Some(LitView::Str("foo")),
            &Param::Str("foo")
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Sym("bar")),
            &Param::Str("foo")
        ));
    }

    #[test]
    fn strset_membership() {
        let set: Vec<String> = vec!["a".into(), "b".into(), "c".into()];
        assert!(match_lit_against_param(
            Some(LitView::Sym("b")),
            &Param::StrSet(&set)
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Sym("z")),
            &Param::StrSet(&set)
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Sym("a")),
            &Param::StrSet(&[])
        ));
    }

    #[test]
    fn int_equality_and_membership() {
        assert!(match_lit_against_param(
            Some(LitView::Int(42)),
            &Param::Int(42)
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Int(42)),
            &Param::Int(7)
        ));
        let set = [1i64, 2, 3];
        assert!(match_lit_against_param(
            Some(LitView::Int(2)),
            &Param::IntSet(&set)
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Int(99)),
            &Param::IntSet(&set)
        ));
    }

    #[test]
    fn bool_equality() {
        assert!(match_lit_against_param(
            Some(LitView::True),
            &Param::Bool(true)
        ));
        assert!(match_lit_against_param(
            Some(LitView::False),
            &Param::Bool(false)
        ));
        assert!(!match_lit_against_param(
            Some(LitView::True),
            &Param::Bool(false)
        ));
    }

    #[test]
    fn type_mismatch_is_miss_not_panic() {
        // Sym vs Int param → miss.
        assert!(!match_lit_against_param(
            Some(LitView::Sym("foo")),
            &Param::Int(42)
        ));
        // Int vs Str param → miss.
        assert!(!match_lit_against_param(
            Some(LitView::Int(42)),
            &Param::Str("foo")
        ));
        // Nil never matches any param.
        assert!(!match_lit_against_param(
            Some(LitView::Nil),
            &Param::Str("nil")
        ));
    }

    #[test]
    fn param_none_always_misses() {
        assert!(!match_lit_against_param(
            Some(LitView::Sym("foo")),
            &Param::None
        ));
        assert!(!match_lit_against_param(
            Some(LitView::Int(42)),
            &Param::None
        ));
        assert!(!match_lit_against_param(None, &Param::None));
    }

    #[test]
    fn no_subject_lit_misses() {
        assert!(!match_lit_against_param(None, &Param::Str("foo")));
        assert!(!match_lit_against_param(None, &Param::Int(42)));
    }

    #[test]
    fn into_param_from_string_ref() {
        let s = String::from("foo");
        assert_eq!((&s).into_param(), Param::Str("foo"));
    }

    #[test]
    fn into_param_from_vec_string() {
        let v: Vec<String> = vec!["a".into(), "b".into()];
        match (&v).into_param() {
            Param::StrSet(slice) => assert_eq!(slice.len(), 2),
            other => panic!("expected StrSet, got {other:?}"),
        }
    }

    #[test]
    fn into_param_from_option_some() {
        let s: Option<String> = Some("foo".into());
        assert_eq!((&s).into_param(), Param::Str("foo"));
    }

    #[test]
    fn into_param_from_option_none() {
        let s: Option<String> = None;
        assert_eq!((&s).into_param(), Param::None);
    }

    #[test]
    fn into_param_from_i64() {
        let n: i64 = 42;
        assert_eq!(n.into_param(), Param::Int(42));
        assert_eq!((&n).into_param(), Param::Int(42));
    }

    #[test]
    fn into_param_from_bool() {
        assert_eq!(true.into_param(), Param::Bool(true));
        let b = false;
        assert_eq!((&b).into_param(), Param::Bool(false));
    }
}
