//! `murphy init` — setup UX for existing repos (C5; ADR 0051).
//!
//! Generates a commented `.murphy.yml` template (with `extends:
//! murphy:<preset>`) plus a `.murphyignore` template so that the very next
//! `murphy lint` returns a sensible result fast (Phase 10 gate 4: lint
//! after init completes in well under 5s on an existing Rails app — the
//! template only narrows discovery via `Exclude` / `.murphyignore`, it
//! never enables extra cops or network fetches).
//!
//! Behaviour:
//!
//! - `murphy init [--preset <name>] [--force] [--hook <tool>] [--from <.rubocop.yml>]`
//! - `--preset` selects a builtin preset (C3; ADR 0050). Both `minimal`
//!   and `murphy:minimal` forms are accepted. Default: `recommended`
//!   (Murphy defaults; documents intent). Unknown names exit 2.
//! - Without `--force`, existing `.murphy.yml` / `.murphyignore` (and any
//!   requested hook scaffold) are never overwritten — the pre-flight
//!   checks all targets first so a re-run is atomic (mirrors
//!   `install --tool all`).
//! - `--from <path>` migrates a `.rubocop.yml` (reusing
//!   `migrate_rubocop_yml_to_murphy_yml`) instead of emitting the fresh
//!   template; the chosen `extends:` is prepended (presets resolve below
//!   user rules, so migrated cop rules always win).
//! - `--hook <tool>` additionally scaffolds a git-hook config via the B8
//!   templates (`lefthook` by default when `--hook` is passed without a
//!   value). Without `--hook`, no hook files are touched.
//! - Baseline files are deliberately NOT generated here: `murphy lint
//!   --generate-baseline` owns that flow (see `docs/guides/baseline.md`);
//!   `init` prints the hint instead so `init` itself stays instant.
//!
//! No `MURPHY_PLUGIN_ABI_VERSION` bump: this is CLI-only scaffolding,
//! the plugin ABI is untouched.

use std::path::{Path, PathBuf};

use super::AppError;

/// `murphy init` options (parsed via clap in `main.rs`).
#[derive(Debug, Clone)]
pub struct InitOptions {
    pub preset: String,
    pub force: bool,
    pub hook: Option<crate::install::HookTool>,
    pub from: Option<PathBuf>,
}

/// Fresh-project `.murphy.yml` body for `preset`.
///
/// Header documents the preset system (C3), `AllCops.Exclude` narrows the
/// two most common generated/vendored Rails paths on top of the bundled
/// defaults (which already skip `node_modules`, `tmp`, `vendor`, `.git`),
/// and the commented examples show per-cop tuning without enabling
/// anything extra (keeps post-init lint fast).
pub fn murphy_yml_template(preset: &str) -> String {
    format!(
        "# Generated by `murphy init`.\n\
         # Presets: minimal, recommended, shopify, rails-strict\n\
         # (see docs/guides/presets.md; both `murphy:<name>` and bare `<name>` work).\n\
         extends: murphy:{preset}\n\
         \n\
         AllCops:\n\
         \x20 # Extra skips on top of the bundled defaults\n\
         \x20 # (defaults already cover node_modules, tmp, vendor, .git).\n\
         \x20 Exclude:\n\
         \x20   - \"db/schema.rb\"\n\
         \x20   - \"vendor/**/*\"\n\
         \x20   - \"tmp/**/*\"\n\
         \n\
         # Per-cop tuning (uncomment to adjust):\n\
         # Style/Documentation:\n\
         #   Enabled: false\n\
         # Metrics/MethodLength:\n\
         #   Max: 15\n"
    )
}

/// Fresh-project `.murphyignore` body (gitignore syntax).
///
/// Only `.murphyignore` prunes discovery besides `AllCops.Exclude`
/// (ambient `.gitignore` is deliberately ignored). `db/schema.rb` is
/// active by default (Rails-generated); the rest are commented examples.
pub fn murphyignore_template() -> String {
    "# Generated by `murphy init`.\n\
     # gitignore syntax. Only this file prunes discovery besides\n\
     # `.murphy.yml` AllCops.Exclude (`.gitignore` is NOT consulted).\n\
     db/schema.rb\n\
     # Uncomment as needed:\n\
     # /vendor/bundle/**/*\n\
     # /tmp/**/*\n\
     # /log/**/*\n\
     # /node_modules/**/*\n"
        .to_string()
}

/// Canonicalize a user `--preset` / `extends` ref or fail with exit 2.
fn canonical_preset(raw: &str) -> Result<&'static str, AppError> {
    murphy_core::presets::normalize_preset_ref(raw).ok_or_else(|| {
        AppError::setup(format!(
            "unknown preset `{raw}` (available: {}) — use one of: {}",
            murphy_core::presets::PRESET_NAMES.join(", "),
            murphy_core::presets::PRESET_NAMES.join(", "),
        ))
    })
}

/// Build the `.murphy.yml` body: fresh template or migrated `--from` file.
fn config_body(canonical: &str, from: Option<&Path>) -> Result<String, AppError> {
    match from {
        None => Ok(murphy_yml_template(canonical)),
        Some(path) => {
            let text = std::fs::read_to_string(path)
                .map_err(|e| AppError::setup(format!("cannot read `{}`: {e}", path.display())))?;
            let migrated = murphy_core::migrate_rubocop_yml_to_murphy_yml(&text)
                .map_err(|e| AppError::setup(e.to_string()))?;
            let mut out = String::new();
            out.push_str("# Generated by `murphy init --from ");
            out.push_str(&path.display().to_string());
            out.push_str("`.\n");
            out.push_str(&format!("extends: murphy:{canonical}\n\n"));
            out.push_str(&migrated);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            Ok(out)
        }
    }
}

/// `murphy init [--preset …] [--force] [--hook …] [--from …]`.
pub fn run_init(opts: &InitOptions) -> Result<u8, AppError> {
    run_init_in(Path::new("."), opts)
}

fn run_init_in(project_root: &Path, opts: &InitOptions) -> Result<u8, AppError> {
    let canonical = canonical_preset(&opts.preset)?;
    let body = config_body(canonical, opts.from.as_deref())?;
    // Validate before touching the disk so a bad migrate never writes.
    murphy_core::MurphyConfig::from_yaml_str(&body)
        .map_err(|e| AppError::setup(format!("generated config is invalid: {e}")))?;
    let ignore_body = murphyignore_template();

    let config_path = project_root.join(".murphy.yml");
    let ignore_path = project_root.join(".murphyignore");

    // Hook scaffolds (B8 templates) when --hook was passed. Resolve here
    // so the pre-flight below stays atomic across all targets.
    let hook_scaffolds: Vec<(PathBuf, String)> = match opts.hook {
        None => Vec::new(),
        Some(tool) => super::install::scaffold_bodies(tool)
            .into_iter()
            .map(|(rel, text)| (project_root.join(rel), text))
            .collect(),
    };

    // Pre-flight: refuse to clobber without --force. Check every target
    // first so a re-run never writes partial scaffolds.
    if !opts.force {
        for path in [&config_path, &ignore_path]
            .into_iter()
            .chain(hook_scaffolds.iter().map(|(p, _)| p))
        {
            if path.exists() {
                return Err(AppError::setup(format!(
                    "File {} already exists (pass --force to overwrite)",
                    path.display()
                )));
            }
        }
    }

    std::fs::write(&config_path, &body)
        .map_err(|e| AppError::setup(format!("cannot write `{}`: {e}", config_path.display())))?;
    println!(
        "Generated {} (preset murphy:{canonical})",
        config_path.display()
    );
    std::fs::write(&ignore_path, &ignore_body)
        .map_err(|e| AppError::setup(format!("cannot write `{}`: {e}", ignore_path.display())))?;
    println!("Generated {}", ignore_path.display());
    for (path, text) in &hook_scaffolds {
        std::fs::write(path, text)
            .map_err(|e| AppError::setup(format!("cannot write `{}`: {e}", path.display())))?;
        println!("Generated {}", path.display());
    }

    if opts.from.is_some() {
        println!("Migrated config from `--from` (review `extends:` + cop rules)");
    }
    println!("Next: `murphy lint` (fast post-init check)");
    println!("  `murphy lint --generate-baseline .murphy-baseline.toml` to freeze legacy offenses");
    if opts.hook.is_none() {
        println!(
            "  `murphy init --hook` (or `murphy install --git-hook`) to add a pre-commit hook"
        );
    }
    Ok(super::EXIT_OK)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opts(preset: &str, force: bool, hook: Option<crate::install::HookTool>) -> InitOptions {
        InitOptions {
            preset: preset.to_string(),
            force,
            hook,
            from: None,
        }
    }

    #[test]
    fn template_contains_preset_and_parses() {
        for name in murphy_core::presets::PRESET_NAMES {
            let body = murphy_yml_template(name);
            assert!(
                body.contains(&format!("extends: murphy:{name}")),
                "got:\n{body}"
            );
            murphy_core::MurphyConfig::from_yaml_str(&body)
                .unwrap_or_else(|e| panic!("template for {name} must parse: {e}"));
        }
    }

    #[test]
    fn ignore_template_names_schema() {
        let body = murphyignore_template();
        assert!(body.contains("db/schema.rb"), "got:\n{body}");
        assert!(body.contains("murphy init"), "got:\n{body}");
    }

    #[test]
    fn unknown_preset_is_setup_error() {
        let err = canonical_preset("murphy:nope").expect_err("must fail");
        assert_eq!(err.code, crate::EXIT_SETUP_ERROR);
        assert!(
            err.message.contains("minimal"),
            "lists presets: {}",
            err.message
        );
    }

    #[test]
    fn init_creates_both_files_and_is_idempotent_without_force() {
        let project = tempfile::tempdir().expect("tempdir");
        let o = opts("recommended", false, None);
        let code: u8 = match run_init_in(project.path(), &o) {
            Ok(c) => c,
            Err(e) => panic!("expected Ok, got: {}", e.message),
        };
        assert_eq!(code, super::super::EXIT_OK);
        let cfg = std::fs::read_to_string(project.path().join(".murphy.yml")).expect("config");
        assert!(cfg.contains("extends: murphy:recommended"), "got:\n{cfg}");
        assert!(
            project.path().join(".murphyignore").exists(),
            "ignore written"
        );
        // Second run without --force refuses and preserves content.
        let err = run_init_in(project.path(), &o).expect_err("must refuse");
        assert_eq!(err.code, crate::EXIT_SETUP_ERROR);
        let cfg2 = std::fs::read_to_string(project.path().join(".murphy.yml")).expect("config");
        assert_eq!(cfg, cfg2, "existing file preserved");
    }

    #[test]
    fn force_overwrites_existing() {
        let project = tempfile::tempdir().expect("tempdir");
        std::fs::write(project.path().join(".murphy.yml"), "custom: true\n").expect("seed");
        std::fs::write(project.path().join(".murphyignore"), "custom\n").expect("seed");
        let o = opts("minimal", true, None);
        match run_init_in(project.path(), &o) {
            Ok(_) => {}
            Err(e) => panic!("force must succeed, got: {}", e.message),
        }
        let cfg = std::fs::read_to_string(project.path().join(".murphy.yml")).expect("config");
        assert!(cfg.contains("extends: murphy:minimal"), "got:\n{cfg}");
    }

    #[test]
    fn bare_preset_name_accepted() {
        let project = tempfile::tempdir().expect("tempdir");
        let o = opts("minimal", false, None);
        match run_init_in(project.path(), &o) {
            Ok(_) => {}
            Err(e) => panic!("bare name must work, got: {}", e.message),
        }
        let cfg = std::fs::read_to_string(project.path().join(".murphy.yml")).expect("config");
        assert!(cfg.contains("extends: murphy:minimal"), "got:\n{cfg}");
    }

    #[test]
    fn from_migrates_rubocop_yml() {
        let project = tempfile::tempdir().expect("tempdir");
        std::fs::write(
            project.path().join(".rubocop.yml"),
            "Lint/Debugger:\n  Enabled: false\n",
        )
        .expect("seed rubocop");
        let o = InitOptions {
            preset: "recommended".to_string(),
            force: false,
            hook: None,
            from: Some(project.path().join(".rubocop.yml")),
        };
        match run_init_in(project.path(), &o) {
            Ok(_) => {}
            Err(e) => panic!("from must succeed, got: {}", e.message),
        }
        let cfg = std::fs::read_to_string(project.path().join(".murphy.yml")).expect("config");
        assert!(cfg.contains("extends: murphy:recommended"), "got:\n{cfg}");
        assert!(cfg.contains("Lint/Debugger"), "migrated rule kept:\n{cfg}");
        murphy_core::MurphyConfig::from_yaml_str(&cfg).expect("migrated config parses");
    }

    #[test]
    fn hook_scaffold_written_with_init() {
        let project = tempfile::tempdir().expect("tempdir");
        let o = opts(
            "recommended",
            false,
            Some(crate::install::HookTool::Lefthook),
        );
        match run_init_in(project.path(), &o) {
            Ok(_) => {}
            Err(e) => panic!("hook must succeed, got: {}", e.message),
        }
        let hook = std::fs::read_to_string(project.path().join("lefthook.yml")).expect("hook");
        assert!(hook.contains("murphy lint"), "got:\n{hook}");
    }

    #[test]
    fn hook_atomic_without_force() {
        let project = tempfile::tempdir().expect("tempdir");
        std::fs::write(project.path().join("lefthook.yml"), "custom: true\n").expect("seed hook");
        let o = opts(
            "recommended",
            false,
            Some(crate::install::HookTool::Lefthook),
        );
        let err = run_init_in(project.path(), &o).expect_err("must refuse");
        assert_eq!(err.code, crate::EXIT_SETUP_ERROR);
        assert!(
            !project.path().join(".murphy.yml").exists(),
            "must not write partial scaffolds"
        );
    }
}
