//! `murphy install --git-hook` — B8 pre-commit / git-hook scaffolds (murphy-fmw.2.8).
//!
//! Generates working hook scaffolds for one of three frameworks:
//!
//! - `lefthook` → `lefthook.yml`
//! - `pre-commit` → `.pre-commit-config.yaml`
//! - `overcommit` → `.overcommit.yml`
//!
//! `--tool all` writes all three. Existing files are never overwritten
//! unless `--force` is passed. Exit `0` on success, `2` on setup errors
//! (missing `--git-hook`, existing file without `--force`, IO failure).
//!
//! No `MURPHY_PLUGIN_ABI_VERSION` bump: this is CLI-only scaffolding,
//! the plugin ABI is untouched.

use std::path::Path;

use super::AppError;

/// Which hook-framework scaffold(s) to generate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HookTool {
    Lefthook,
    PreCommit,
    Overcommit,
    All,
}

/// `murphy install --git-hook` options (parsed via clap in `main.rs`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstallOptions {
    pub git_hook: bool,
    pub tool: HookTool,
    pub force: bool,
}

/// Scaffold target: output path + template body.
struct Scaffold {
    path: &'static str,
    body: String,
    activate_hint: &'static str,
}

/// lefthook scaffold body (`lefthook.yml`).
pub fn lefthook_yml() -> String {
    "# Generated by `murphy install --git-hook --tool lefthook`.\n\
     # Requires lefthook: https://github.com/evilmartians/lefthook\n\
     # Activate with: lefthook install\n\
     pre-commit:\n\
     \x20 parallel: true\n\
     \x20 commands:\n\
     \x20   murphy:\n\
     \x20     glob: \"*.rb\"\n\
     \x20     run: murphy lint --format progress {staged_files}\n"
        .to_string()
}

/// pre-commit-framework scaffold body (`.pre-commit-config.yaml`).
pub fn pre_commit_config_yaml() -> String {
    "# Generated by `murphy install --git-hook --tool pre-commit`.\n\
     # Requires pre-commit: https://pre-commit.com/#installation\n\
     # Activate with: pre-commit install\n\
     repos:\n\
     \x20 - repo: local\n\
     \x20   hooks:\n\
     \x20     - id: murphy\n\
     \x20       name: murphy lint\n\
     \x20       entry: murphy lint --format progress\n\
     \x20       language: system\n\
     \x20       types: [ruby]\n\
     \x20       pass_filenames: true\n"
        .to_string()
}

/// overcommit scaffold body (`.overcommit.yml`).
pub fn overcommit_yml() -> String {
    "# Generated by `murphy install --git-hook --tool overcommit`.\n\
     # Requires overcommit: https://github.com/sds/overcommit\n\
     # Activate with: overcommit --install && overcommit --sign\n\
     PreCommit:\n\
     \x20 Murphy:\n\
     \x20   enabled: true\n\
     \x20   description: Run murphy lint on staged Ruby files\n\
     \x20   required_executable: murphy\n\
     \x20   command: ['murphy', 'lint', '--format', 'progress']\n\
     \x20   include: '**/*.rb'\n"
        .to_string()
}

fn scaffolds_for(tool: HookTool) -> Vec<Scaffold> {
    match tool {
        HookTool::Lefthook => vec![Scaffold {
            path: "lefthook.yml",
            body: lefthook_yml(),
            activate_hint: "lefthook install",
        }],
        HookTool::PreCommit => vec![Scaffold {
            path: ".pre-commit-config.yaml",
            body: pre_commit_config_yaml(),
            activate_hint: "pre-commit install",
        }],
        HookTool::Overcommit => vec![Scaffold {
            path: ".overcommit.yml",
            body: overcommit_yml(),
            activate_hint: "overcommit --install",
        }],
        HookTool::All => vec![
            Scaffold {
                path: "lefthook.yml",
                body: lefthook_yml(),
                activate_hint: "lefthook install",
            },
            Scaffold {
                path: ".pre-commit-config.yaml",
                body: pre_commit_config_yaml(),
                activate_hint: "pre-commit install",
            },
            Scaffold {
                path: ".overcommit.yml",
                body: overcommit_yml(),
                activate_hint: "overcommit --install",
            },
        ],
    }
}

/// `murphy install --git-hook [--tool …] [--force]`.
pub fn run_install(opts: &InstallOptions) -> Result<u8, AppError> {
    if !opts.git_hook {
        return Err(AppError::setup(
            "nothing to install: pass `--git-hook` (e.g. `murphy install --git-hook --tool lefthook`)",
        ));
    }
    let scaffolds = scaffolds_for(opts.tool);
    // Pre-flight: refuse to clobber without --force so a re-run never
    // silently discards user edits. Check all targets first for atomicity.
    if !opts.force {
        for scaffold in &scaffolds {
            if Path::new(scaffold.path).exists() {
                return Err(AppError::setup(format!(
                    "File {} already exists (pass --force to overwrite)",
                    scaffold.path
                )));
            }
        }
    }
    for scaffold in &scaffolds {
        std::fs::write(scaffold.path, &scaffold.body)
            .map_err(|e| AppError::setup(format!("failed to write {}: {e}", scaffold.path)))?;
        println!(
            "Generated {} (activate with `{}`)",
            scaffold.path, scaffold.activate_hint
        );
    }
    Ok(super::EXIT_OK)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lefthook_template_runs_murphy_on_staged_ruby() {
        let body = lefthook_yml();
        assert!(body.contains("murphy lint"), "got:\n{body}");
        assert!(body.contains("{staged_files}"), "got:\n{body}");
        assert!(body.contains("*.rb"), "got:\n{body}");
        assert!(body.contains("pre-commit:"), "got:\n{body}");
    }

    #[test]
    fn pre_commit_template_is_local_system_hook() {
        let body = pre_commit_config_yaml();
        assert!(body.contains("repo: local"), "got:\n{body}");
        assert!(body.contains("murphy lint"), "got:\n{body}");
        assert!(body.contains("language: system"), "got:\n{body}");
        assert!(body.contains("ruby"), "got:\n{body}");
    }

    #[test]
    fn overcommit_template_calls_murphy_lint() {
        let body = overcommit_yml();
        assert!(body.contains("PreCommit:"), "got:\n{body}");
        assert!(body.contains("murphy"), "got:\n{body}");
        assert!(body.contains("lint"), "got:\n{body}");
        assert!(body.contains("*.rb"), "got:\n{body}");
    }

    #[test]
    fn all_selects_three_scaffolds() {
        assert_eq!(scaffolds_for(HookTool::All).len(), 3);
        assert_eq!(scaffolds_for(HookTool::Lefthook).len(), 1);
        assert_eq!(scaffolds_for(HookTool::PreCommit).len(), 1);
        assert_eq!(scaffolds_for(HookTool::Overcommit).len(), 1);
    }

    #[test]
    fn missing_git_hook_flag_is_setup_error() {
        let opts = InstallOptions {
            git_hook: false,
            tool: HookTool::Lefthook,
            force: false,
        };
        let err = run_install(&opts).expect_err("must fail without --git-hook");
        assert_eq!(err.code, crate::EXIT_SETUP_ERROR);
    }
}
